vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: /upload/images/product
            upload_destination: '%kernel.project_dir%/public/upload/images/product'
        admission:
            uri_prefix: /upload/files
            upload_destination: '%kernel.project_dir%/public/upload/files'
